"use client";

import React, { useState, useRef } from "react";
import Link from "next/link";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  Camera,
  Dumbbell,
  Utensils,
  TrendingUp,
  Target,
  Bot,
  ArrowRight,
  CheckCircle2,
  Users,
  Star,
  Trophy,
  Flame,
  ShieldCheck,
  ChevronRight,
  ChevronDown,
  Zap,
  ShoppingCart,
  Copy,
  Clock,
  Droplets,
  RotateCcw,
  Check,
  Award,
  HeartPulse,
  Scale,
  Layers,
  MessageSquare,
  Eye,
  Sliders,
  CheckCheck,
  Smartphone,
  Sparkle,
  Sparkles as SparklesIcon,
  HelpCircle
} from "lucide-react";
import { toast } from "sonner";

export function FitnessLandingPage() {
  const [activeTab, setActiveTab] = useState<"workout" | "nutrition" | "grocery" | "scanner" | "comparison" | "coach">("workout");
  const [groceryMode, setGroceryMode] = useState<"weekly" | "monthly">("weekly");
  const [checkedGrocery, setCheckedGrocery] = useState<Record<string, boolean>>({ "item-1": true, "item-3": true });
  const [compareMode, setCompareMode] = useState<"slider" | "side-by-side">("slider");
  const [compareAngle, setCompareAngle] = useState<"front" | "side" | "back">("front");
  const [compareSliderPos, setCompareSliderPos] = useState(50);
  const sliderContainerRef = useRef<HTMLDivElement>(null);

  const handleSliderInteraction = (clientX: number) => {
    if (!sliderContainerRef.current) return;
    const rect = sliderContainerRef.current.getBoundingClientRect();
    const x = clientX - rect.left;
    const percent = Math.max(5, Math.min(95, (x / rect.width) * 100));
    setCompareSliderPos(Math.round(percent));
  };
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [copiedBlinkit, setCopiedBlinkit] = useState(false);

  const toggleGroceryCheck = (id: string) => {
    setCheckedGrocery((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleCopyMockList = () => {
    const text = `🛒 GrindLog Smart Grocery List (${groceryMode === "weekly" ? "Weekly Run" : "Monthly Stock"})
━━━━━━━━━━━━━━━━━━━━━
🥛 Dairy & High-Protein:
${checkedGrocery["item-1"] ? "✅" : "▫️"} Fresh Paneer (Raw) — ${groceryMode === "weekly" ? "560 g (~₹253)" : "2.25 kg (~₹1012)"}
${checkedGrocery["item-2"] ? "✅" : "▫️"} Soya Chunks — ${groceryMode === "weekly" ? "1 pack (~₹60)" : "4 packs (~₹230)"}
▫️ Farm Eggs — ${groceryMode === "weekly" ? "12 pcs (~₹90)" : "48 pcs (~₹360)"}

🌾 Grains & Staples:
${checkedGrocery["item-3"] ? "✅" : "▫️"} Brown Rice — ${groceryMode === "weekly" ? "1.25 kg (~₹85)" : "5 kg (~₹200)"}
▫️ Whole Wheat Atta — ${groceryMode === "weekly" ? "1.5 kg (~₹75)" : "6 kg (~₹290)"}
━━━━━━━━━━━━━━━━━━━━━
💵 Estimated: ${groceryMode === "weekly" ? "₹1,229" : "₹4,917"}
📱 Generated by GrindLog AI`;

    if (typeof navigator !== "undefined" && navigator.clipboard) {
      navigator.clipboard.writeText(text);
      setCopiedBlinkit(true);
      toast.success("Sample grocery list copied! Ready for Blinkit or WhatsApp.");
      setTimeout(() => setCopiedBlinkit(false), 2500);
    }
  };

  // 8 Core App Superpowers
  const superpowers = [
    {
      icon: Utensils,
      title: "100% Indian Nutrition Engine",
      badge: "Target-Scaled",
      desc: "Culturally authentic recipes (Besan Cheela, Rajma Chawal, Dal Tadka, Paneer Bhurji) scaled with exact gram precision to your calorie & macro targets.",
      highlight: "Veg, Non-Veg, Egg & Vegan",
      color: "from-lime-500/15 to-emerald-500/5",
      accent: "#ADFF00"
    },
    {
      icon: ShoppingCart,
      title: "Smart Grocery & Blinkit Order",
      badge: "NEW FEATURE",
      desc: "Derives groceries straight from your active meal plan with a Weekly Run vs Monthly Stock toggle and 1-tap copy for Blinkit, Zepto, or WhatsApp.",
      highlight: "Aisle Grouped & Budget-Checked",
      color: "from-emerald-500/15 to-teal-500/5",
      accent: "#34D399"
    },
    {
      icon: Dumbbell,
      title: "Live PR & Workout Logger",
      badge: "Hypertrophy Science",
      desc: "Set-by-set weight & rep tracking with automatic rest countdown timer, previous set memory, PR celebrations, and animated exercise guides.",
      highlight: "Gym, Home & Dumbbell Splits",
      color: "from-amber-500/15 to-lime-500/5",
      accent: "#FBBF24"
    },
    {
      icon: Camera,
      title: "AI Vision Body Scanner",
      badge: "Computer Vision",
      desc: "Instant front, side, and back computer vision scan analyzes posture tilt, muscle symmetry, and body fat without expensive DEXA scans.",
      highlight: "100% Private & Auto-Deleted",
      color: "from-cyan-500/15 to-blue-500/5",
      accent: "#38BDF8"
    },
    {
      icon: Camera,
      title: "Before & After Photo Compare",
      badge: "Split Slider",
      desc: "Side-by-side timeline and interactive split comparison slider to track Day 1 vs Current Day changes across Front, Side, and Back angles with milestone metrics.",
      highlight: "Split Slider & Goal Overlay",
      color: "from-cyan-500/15 to-emerald-500/5",
      accent: "#38BDF8"
    },
    {
      icon: Sliders,
      title: "1-Tap Macro-Matched Swaps",
      badge: "Zero Deficit",
      desc: "Bored of a meal? Swap Paneer Bhurji for Moong Dal Cheela with 1 tap. The engine recalculates ingredient weights to hit the exact same macros.",
      highlight: "Bi-Weekly Menu Rotations",
      color: "from-purple-500/15 to-lime-500/5",
      accent: "#C084FC"
    },
    {
      icon: Clock,
      title: "Smart Habits & Reminders",
      badge: "Zero-Lag Alerts",
      desc: "Never miss hydration goals, pre-workout fuel, training sessions, or post-workout protein with push notifications and water tracking.",
      highlight: "Fast & Mobile Battery Friendly",
      color: "from-blue-500/15 to-emerald-500/5",
      accent: "#60A5FA"
    },
    {
      icon: Bot,
      title: "24/7 Adaptive AI Coach",
      badge: "Plateau Breaker",
      desc: "Your personal AI fitness coach Luna monitors daily check-ins, adjusts training volume when you stall, and adapts if you miss workouts.",
      highlight: "Real-time AI Chat Coach",
      color: "from-lime-500/20 to-emerald-500/10",
      accent: "#ADFF00"
    },
    {
      icon: Scale,
      title: "Budget-First Guarantee",
      badge: "₹2,000–₹5,000 / mo",
      desc: "Engineered specifically for Indian student & family budgets. Prioritizes high protein-per-rupee staples like soya chunks, eggs, curd, and sattu.",
      highlight: "Zero Expensive Supplements Needed",
      color: "from-emerald-500/15 to-lime-500/5",
      accent: "#10B981"
    }
  ];

  // Comparison Data
  const comparisonItems = [
    {
      feature: "Authentic Indian Food Recipes & Regional Macros",
      grindlog: true,
      westernApps: false,
      trainer: "Hit or Miss"
    },
    {
      feature: "Before & After Photo Comparison & Split Slider",
      grindlog: true,
      westernApps: "Paid Add-on",
      trainer: "Manual photos"
    },
    {
      feature: "Smart Grocery List + 1-Tap Blinkit / WhatsApp Export",
      grindlog: true,
      westernApps: false,
      trainer: false
    },
    {
      feature: "AI Vision Body Scanning & Posture Analysis",
      grindlog: true,
      westernApps: false,
      trainer: false
    },
    {
      feature: "Instant 1-Tap Macro-Identical Meal Swaps",
      grindlog: true,
      westernApps: false,
      trainer: false
    },
    {
      feature: "Live Workout Set Logger with PRs & Auto-Rest Timer",
      grindlog: true,
      westernApps: "Basic (Paid)",
      trainer: "Manual Notebook"
    },
    {
      feature: "24/7 Real-Time AI Coach for Questions & Plateau Adjustments",
      grindlog: true,
      westernApps: false,
      trainer: "Slow WhatsApp replies"
    },
    {
      feature: "Optimized for Indian Budgets (₹2k–₹5k / mo)",
      grindlog: true,
      westernApps: false,
      trainer: "Pushes expensive whey"
    },
    {
      feature: "Cost",
      grindlog: "Free Preview / ₹499 Pro",
      westernApps: "₹1,200+/mo",
      trainer: "₹12,000 - ₹20,000/mo"
    }
  ];

  // FAQ Items
  const faqItems = [
    {
      q: "Does GrindLog work for pure vegetarians and vegans?",
      a: "Yes, 100%! GrindLog was built in India for Indian diets. You can set your preference to Vegetarian, Eggetarian, Vegan, or Non-Vegetarian. You'll get authentic dishes like Besan Cheela, Moong Dal Cheela, Paneer Bhurji, Soya Matar Curry, and Rajma Chawal with exact gram portions calculated to hit 120g–160g+ of daily protein without forcing expensive protein powders."
    },
    {
      q: "How does the Smart Grocery List & Blinkit / WhatsApp export work?",
      a: "GrindLog looks at your active 7-day meal plan and automatically aggregates every ingredient into retail packaging units (e.g. 560g paneer, 1 pack soya chunks, 12 eggs). You can toggle between 'Weekly Run' and 'Monthly Stock'. Tapping 'Copy for Blinkit / WhatsApp' generates a formatted list organized by supermarket aisle that you can paste directly into quick-commerce apps or send to your roommate, cook, or local kirana store."
    },
    {
      q: "What if I live in a PG or hostel with no kitchen access?",
      a: "GrindLog has a dedicated 'PG / Hostel Food' environment setting. It assumes your core meals (mess breakfast, lunch, dinner) are provided, and smartly adds affordable, high-protein add-ons (boiled eggs, curd, paneer, roasted chana, fruits) to hit your protein and calorie targets while keeping extra food costs under ₹50–₹70/day."
    },
    {
      q: "Can I use GrindLog if I work out at home without gym equipment?",
      a: "Absolutely. During onboarding, choose from Commercial Gym, Dumbbells Only, Resistance Bands, or No Equipment / Bodyweight. The AI coach generates a progressive split tailored to your exact equipment and adjusts difficulty as you get stronger."
    },
    {
      q: "How does the Before & After Photo Comparison work?",
      a: "GrindLog lets you take or upload check-in photos across front, left, right, and back angles. You can inspect your transformation in two modes: a side-by-side timeline or an interactive Split Comparison Slider that you drag horizontally to reveal your exact physique changes (fat loss, waist reduction, muscle hypertrophy) over time. You can also upload your dream goal physique to compare your current shape against your target roadmap."
    },
    {
      q: "Are my body scan photos private and secure?",
      a: "Yes. Your privacy is paramount. Scan photos are processed via secure computer vision to extract posture alignment and body fat estimates, and are never shared or made public. You can also skip photo uploads and enter standard biometrics instead."
    }
  ];

  return (
    <div className="min-h-screen bg-[#070C07] text-white selection:bg-[#ADFF00] selection:text-black font-sans relative overflow-x-hidden">
      
      {/* Glow Orbs background */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1100px] h-[550px] bg-[#ADFF00]/10 blur-[150px] pointer-events-none rounded-full" />
      <div className="absolute top-[850px] right-0 w-[600px] h-[600px] bg-emerald-500/10 blur-[180px] pointer-events-none rounded-full" />
      <div className="absolute top-[2200px] left-0 w-[500px] h-[500px] bg-[#ADFF00]/5 blur-[160px] pointer-events-none rounded-full" />

      {/* Top Announcement Bar */}
      <div className="bg-gradient-to-r from-[#122311] via-[#1A3319] to-[#122311] border-b border-[#254223] py-2 px-4 text-center text-xs font-bold text-white/90">
        <div className="max-w-7xl mx-auto flex items-center justify-center gap-2">
          <span className="inline-flex items-center gap-1 bg-[#ADFF00] text-black text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
            NEW
          </span>
          <span>Smart Grocery List with 1-Tap Blinkit & WhatsApp Export is live!</span>
          <a href="#showcase" className="text-[#ADFF00] hover:underline flex items-center gap-0.5">
            <span>Explore live</span>
            <ArrowRight className="w-3 h-3" />
          </a>
        </div>
      </div>

      {/* Navigation Header */}
      <header className="sticky top-0 z-50 backdrop-blur-xl bg-[#070C07]/85 border-b border-[#1A2619]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-10 h-10 rounded-2xl bg-[#ADFF00] text-black flex items-center justify-center font-black text-xl shadow-[0_0_20px_rgba(173,255,0,0.4)] group-hover:scale-105 transition-transform">
              G
            </div>
            <div className="flex flex-col">
              <span className="font-extrabold text-xl tracking-tight leading-none text-white">
                GRINDLOG<span className="text-[#ADFF00]">.AI</span>
              </span>
              <span className="text-[10px] text-gray-400 tracking-widest font-semibold uppercase mt-0.5">
                Fitness AI OS
              </span>
            </div>
          </Link>

          {/* Desktop Nav Links */}
          <nav className="hidden md:flex items-center gap-7 text-sm font-semibold text-gray-300">
            <a href="#showcase" className="hover:text-[#ADFF00] transition-colors">Live App</a>
            <a href="#features" className="hover:text-[#ADFF00] transition-colors">All Features</a>
            <a href="#comparison" className="hover:text-[#ADFF00] transition-colors">Why GrindLog</a>
            <a href="#faq" className="hover:text-[#ADFF00] transition-colors">FAQ</a>
          </nav>

          <div className="flex items-center gap-3 sm:gap-4">
            <Link
              href="/auth/signin?redirect=/"
              className="text-sm font-semibold text-gray-300 hover:text-white transition-colors px-3 sm:px-4 py-2 rounded-full hover:bg-white/5"
            >
              Log in
            </Link>
            <Link
              href="/auth/signup?redirect=/onboarding"
              className="relative group px-4 sm:px-5 py-2.5 rounded-full text-xs sm:text-sm font-black uppercase tracking-wider text-black bg-[#ADFF00] hover:bg-[#c4ff33] transition-all shadow-[0_0_25px_rgba(173,255,0,0.35)] flex items-center gap-2 active:scale-95"
            >
              <span>Start Free</span>
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-12 sm:pt-20 pb-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        {/* Top Badge */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-8 shadow-inner"
        >
          <Sparkles className="w-3.5 h-3.5 animate-pulse text-[#ADFF00]" />
          <span>REVOLUTIONIZING FITNESS FOR INDIAN LIFESTYLES</span>
        </motion.div>

        {/* Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-4xl sm:text-6xl md:text-7xl font-black tracking-tight max-w-5xl mx-auto leading-[1.08] text-white"
        >
          Your Body. Your Goal. <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#ADFF00] via-lime-300 to-emerald-400 drop-shadow-[0_0_35px_rgba(173,255,0,0.3)]">
            Your Intelligent AI Coach.
          </span>
        </motion.h1>

        {/* Subheadline */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mt-6 text-base sm:text-xl text-gray-300 max-w-3xl mx-auto font-normal leading-relaxed"
        >
          Upload your physique photos for instant AI computer vision assessment, then get hyper-personalized Indian meal plans, budget-scaled grocery lists, and adaptive workout splits that evolve as you progress.
        </motion.p>

        {/* CTA Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Link
            href="/auth/signup?redirect=/onboarding"
            className="w-full sm:w-auto px-9 py-4 rounded-full text-base font-black uppercase tracking-wider text-black bg-[#ADFF00] hover:bg-[#c6ff47] transition-all shadow-[0_0_35px_rgba(173,255,0,0.45)] hover:scale-105 active:scale-95 flex items-center justify-center gap-3 group"
          >
            <span>Start My Free Transformation</span>
            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </Link>

          <a
            href="#showcase"
            className="w-full sm:w-auto px-8 py-4 rounded-full text-base font-bold text-gray-200 bg-[#121A12] border border-[#233522] hover:bg-[#1A261A] hover:border-[#ADFF00]/40 transition-all flex items-center justify-center gap-2"
          >
            <span>Explore Live Showcase</span>
            <ChevronDown className="w-4 h-4" />
          </a>
        </motion.div>

        {/* Social Proof Badges */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-10 pt-6 border-t border-white/5 max-w-2xl mx-auto flex flex-wrap items-center justify-center gap-6 sm:gap-10 text-xs font-semibold text-gray-400"
        >
          <div className="flex items-center gap-1.5">
            <div className="flex text-[#ADFF00]">
              {[1, 2, 3, 4, 5].map((i) => (
                <Star key={i} className="w-3.5 h-3.5 fill-current" />
              ))}
            </div>
            <span className="text-white font-bold">4.9/5 Rating</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Users className="w-4 h-4 text-[#ADFF00]" />
            <span>14,800+ Active Members</span>
          </div>
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>100% Indian Diet Compatible</span>
          </div>
        </motion.div>
      </section>

      {/* INTERACTIVE SHOWCASE: The Live App Experience */}
      <section id="showcase" className="py-16 sm:py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-4">
            <Smartphone className="w-4 h-4" />
            <span>Interactive App Preview</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-black tracking-tight text-white">
            See the GrindLog Engine in Action
          </h2>
          <p className="mt-4 text-sm sm:text-base text-gray-400">
            Click between the 5 superpowers below to explore how GrindLog runs your daily workouts, nutrition, and shopping.
          </p>
        </div>

        {/* Product Showcase Tabs */}
        <div className="flex items-center justify-center gap-2 flex-wrap mb-8">
          {[
            { id: "workout", label: "Workout Logger", icon: Dumbbell },
            { id: "nutrition", label: "Indian Meals", icon: Utensils },
            { id: "grocery", label: "Smart Grocery", icon: ShoppingCart },
            { id: "comparison", label: "Photo Compare", icon: Camera },
            { id: "scanner", label: "Body Scanner", icon: Sparkles },
            { id: "coach", label: "24/7 AI Coach", icon: Bot },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-2 px-4 sm:px-5 py-2.5 rounded-full text-xs sm:text-sm font-extrabold uppercase tracking-wider transition-all duration-150 ${
                  isActive
                    ? "bg-[#ADFF00] text-black shadow-[0_0_20px_rgba(173,255,0,0.35)] scale-105"
                    : "bg-[#121E12] border border-[#1A2619] text-white/70 hover:text-white hover:bg-white/5"
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Showcase Canvas Screen */}
        <div className="max-w-4xl mx-auto rounded-3xl bg-[#0D150D] border border-[#1E2E1D] p-4 sm:p-8 shadow-[0_20px_80px_rgba(0,0,0,0.9)] backdrop-blur-2xl">
          <AnimatePresence mode="wait">
            
            {/* 1. WORKOUT LOGGER PREVIEW */}
            {activeTab === "workout" && (
              <motion.div
                key="workout"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-6"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#ADFF00]">
                      Active Live Session · Day 2
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black text-white">
                      Push Hypertrophy (Chest, Shoulders & Triceps)
                    </h3>
                  </div>
                  <div className="flex items-center gap-2 bg-[#162616] border border-[#ADFF00]/20 px-3 py-1.5 rounded-full text-xs font-bold text-[#ADFF00]">
                    <Clock className="w-3.5 h-3.5" />
                    <span>01:15 Rest Timer</span>
                  </div>
                </div>

                {/* Exercise Set Tracker Cards */}
                <div className="space-y-3">
                  <div className="bg-[#121E12] border border-[#1A2619] rounded-2xl p-4">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-lg bg-[#ADFF00]/10 text-[#ADFF00] flex items-center justify-center font-bold text-xs">
                          1
                        </div>
                        <div>
                          <h4 className="text-sm font-bold text-white">Incline Dumbbell Bench Press</h4>
                          <p className="text-[11px] text-white/50">Target: 3 sets × 8–10 reps · RPE 8</p>
                        </div>
                      </div>
                      <span className="text-xs font-black text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">
                        NEW PR 🏆
                      </span>
                    </div>

                    <div className="grid grid-cols-4 gap-2 text-center text-xs font-bold">
                      <div className="bg-black/30 p-2 rounded-lg border border-white/5">
                        <span className="text-[9px] text-white/40 block">SET</span>1
                      </div>
                      <div className="bg-black/30 p-2 rounded-lg border border-white/5">
                        <span className="text-[9px] text-white/40 block">PREVIOUS</span>30 kg × 10
                      </div>
                      <div className="bg-[#ADFF00]/10 p-2 rounded-lg border border-[#ADFF00]/30 text-[#ADFF00]">
                        <span className="text-[9px] text-[#ADFF00]/60 block">WEIGHT</span>32 kg
                      </div>
                      <div className="bg-[#ADFF00] text-black p-2 rounded-lg flex items-center justify-center gap-1 font-black">
                        <Check className="w-3.5 h-3.5 stroke-[3]" /> Done
                      </div>
                    </div>
                  </div>

                  <div className="bg-[#121E12] border border-[#1A2619] rounded-2xl p-4 opacity-85">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-lg bg-white/5 text-white/60 flex items-center justify-center font-bold text-xs">
                          2
                        </div>
                        <div>
                          <h4 className="text-sm font-bold text-white">Standing Overhead Barbell Press</h4>
                          <p className="text-[11px] text-white/50">Target: 3 sets × 8–10 reps</p>
                        </div>
                      </div>
                      <span className="text-xs font-bold text-white/40">Next Up</span>
                    </div>
                  </div>
                </div>

                <div className="p-4 rounded-xl bg-[#121F12] border border-[#213520] flex items-center justify-between text-xs text-gray-300">
                  <span className="flex items-center gap-2">
                    <Flame className="w-4 h-4 text-[#ADFF00]" />
                    Estimated burn: <strong>380 kcal</strong> · Rest timer auto-syncs between sets
                  </span>
                  <span className="text-[#ADFF00] font-bold">500+ Exercise Animations</span>
                </div>
              </motion.div>
            )}

            {/* 2. INDIAN NUTRITION PREVIEW */}
            {activeTab === "nutrition" && (
              <motion.div
                key="nutrition"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-6"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#ADFF00]">
                      Vegetarian Lean Muscle Split · Week A Rotation
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black text-white">
                      Today's Target: 2,003 kcal · 152g Protein
                    </h3>
                  </div>
                  <div className="text-right">
                    <span className="text-xs font-bold text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full">
                      Exact Gram Precision
                    </span>
                  </div>
                </div>

                {/* Macro Target Bars */}
                <div className="grid grid-cols-3 gap-2 sm:gap-4 text-center">
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-wider block">Protein</span>
                    <span className="text-lg font-black text-[#ADFF00]">152g</span>
                    <span className="text-[10px] text-white/50 block">Target: 152g</span>
                  </div>
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-wider block">Carbs</span>
                    <span className="text-lg font-black text-white">225g</span>
                    <span className="text-[10px] text-white/50 block">Fuel for training</span>
                  </div>
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-wider block">Fat</span>
                    <span className="text-lg font-black text-white">55g</span>
                    <span className="text-[10px] text-white/50 block">Hormone health</span>
                  </div>
                </div>

                {/* Real Dish Cards */}
                <div className="space-y-2.5">
                  <div className="p-3.5 bg-[#121E12] border border-[#1A2619] rounded-2xl flex items-center justify-between">
                    <div>
                      <span className="text-[10px] font-bold text-[#ADFF00] uppercase tracking-wider">Breakfast</span>
                      <h4 className="text-sm font-bold text-white">Besan Cheela (2 cheelas) + Chilled Dahi</h4>
                      <p className="text-xs text-white/50 mt-0.5">32g Protein · 410 kcal</p>
                    </div>
                    <span className="text-xs px-2.5 py-1 rounded-full bg-white/5 border border-white/10 text-white/70 font-semibold">
                      🔄 1-Tap Swap
                    </span>
                  </div>

                  <div className="p-3.5 bg-[#121E12] border border-[#1A2619] rounded-2xl flex items-center justify-between">
                    <div>
                      <span className="text-[10px] font-bold text-[#ADFF00] uppercase tracking-wider">Lunch</span>
                      <h4 className="text-sm font-bold text-white">Homestyle Rajma Chawal + Cucumber Salad</h4>
                      <p className="text-xs text-white/50 mt-0.5">38g Protein · 650 kcal</p>
                    </div>
                    <span className="text-xs px-2.5 py-1 rounded-full bg-[#ADFF00]/10 border border-[#ADFF00]/20 text-[#ADFF00] font-semibold">
                      Core Meal
                    </span>
                  </div>

                  <div className="p-3.5 bg-[#121E12] border border-[#1A2619] rounded-2xl flex items-center justify-between">
                    <div>
                      <span className="text-[10px] font-bold text-amber-400 uppercase tracking-wider">Pre-Workout (Light Fuel)</span>
                      <h4 className="text-sm font-bold text-white">1 Ripe Banana + Roasted Chana (50g)</h4>
                      <p className="text-xs text-white/50 mt-0.5">14g Protein · 240 kcal · &lt; 2g Fat</p>
                    </div>
                    <span className="text-xs font-bold text-emerald-400">Zero Sluggishness</span>
                  </div>
                </div>
              </motion.div>
            )}

            {/* 3. SMART GROCERY PREVIEW */}
            {activeTab === "grocery" && (
              <motion.div
                key="grocery"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-6"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4 flex-wrap gap-2">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#ADFF00]">
                      Derived Automatically from Active Meal Plan
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black text-white">
                      Smart Grocery & Quick-Commerce Order
                    </h3>
                  </div>

                  {/* Toggle Weekly vs Monthly */}
                  <div className="bg-black/40 border border-[#1A2619] p-1 rounded-xl flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => setGroceryMode("weekly")}
                      className={`px-3 py-1 rounded-lg text-xs font-black uppercase transition-all ${
                        groceryMode === "weekly" ? "bg-[#ADFF00] text-black" : "text-white/60 hover:text-white"
                      }`}
                    >
                      Weekly Run (7-Day)
                    </button>
                    <button
                      type="button"
                      onClick={() => setGroceryMode("monthly")}
                      className={`px-3 py-1 rounded-lg text-xs font-black uppercase transition-all ${
                        groceryMode === "monthly" ? "bg-[#ADFF00] text-black" : "text-white/60 hover:text-white"
                      }`}
                    >
                      Monthly Stock (30-Day)
                    </button>
                  </div>
                </div>

                {/* Progress & Budget Summary */}
                <div className="bg-[#121E12] border border-[#1A2619] rounded-2xl p-4 flex items-center justify-between">
                  <div>
                    <p className="text-[10px] uppercase font-bold text-white/40">Shopping Checklist</p>
                    <p className="text-lg font-black text-white">
                      {Object.values(checkedGrocery).filter(Boolean).length} of 4 items packed
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-[10px] uppercase font-bold text-white/40">Estimated Spend</p>
                    <p className="text-lg font-black text-[#ADFF00]">
                      {groceryMode === "weekly" ? "₹1,229" : "₹4,917"}
                      <span className="text-xs font-normal text-white/40"> / ₹5,000 budget</span>
                    </p>
                  </div>
                </div>

                {/* Interactive Items Checklist */}
                <div className="space-y-2">
                  {[
                    { id: "item-1", name: "Fresh Paneer (Raw)", weeklyQty: "560 g", monthlyQty: "2.25 kg", priceWeekly: 253, priceMonthly: 1012, cat: "Dairy & High-Protein" },
                    { id: "item-2", name: "Soya Chunks (Raw / Dry)", weeklyQty: "1 pack", monthlyQty: "4 packs", priceWeekly: 60, priceMonthly: 230, cat: "Dairy & High-Protein" },
                    { id: "item-3", name: "Brown Rice", weeklyQty: "1.25 kg", monthlyQty: "5 kg", priceWeekly: 85, priceMonthly: 200, cat: "Grains & Staples" },
                    { id: "item-4", name: "Mixed Fresh Veggies", weeklyQty: "750 g", monthlyQty: "3 kg", priceWeekly: 75, priceMonthly: 300, cat: "Fresh Produce" },
                  ].map((it) => {
                    const isChecked = Boolean(checkedGrocery[it.id]);
                    return (
                      <div
                        key={it.id}
                        onClick={() => toggleGroceryCheck(it.id)}
                        className={`p-3.5 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                          isChecked ? "bg-[#0E170E]/50 border-white/5 opacity-60" : "bg-[#121E12] border-[#1A2619] hover:border-[#ADFF00]/40"
                        }`}
                      >
                        <div className="flex items-center gap-3">
                          <button
                            type="button"
                            className={`w-5 h-5 rounded flex items-center justify-center transition-all ${
                              isChecked ? "bg-[#ADFF00] text-black" : "border border-white/20"
                            }`}
                          >
                            {isChecked && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                          </button>
                          <div>
                            <h5 className={`text-sm font-bold ${isChecked ? "line-through text-white/40" : "text-white"}`}>
                              {it.name}
                            </h5>
                            <span className="text-xs font-bold text-[#ADFF00]">
                              {groceryMode === "weekly" ? it.weeklyQty : it.monthlyQty}
                            </span>
                          </div>
                        </div>
                        <span className={`text-sm font-black ${isChecked ? "line-through text-white/30" : "text-white"}`}>
                          ₹{groceryMode === "weekly" ? it.priceWeekly : it.priceMonthly}
                        </span>
                      </div>
                    );
                  })}
                </div>

                {/* Blinkit Export Button */}
                <button
                  type="button"
                  onClick={handleCopyMockList}
                  className="w-full py-3.5 rounded-xl bg-[#ADFF00] hover:bg-[#b8ff1f] active:scale-[0.99] text-black font-black text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-[0_4px_20px_rgba(173,255,0,0.3)] transition-all"
                >
                  {copiedBlinkit ? (
                    <>
                      <Check className="w-4 h-4 stroke-[3]" />
                      Copied for Blinkit / WhatsApp!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      1-Tap Copy for Blinkit, Zepto or WhatsApp
                    </>
                  )}
                </button>
              </motion.div>
            )}

            {/* 4. PHOTO COMPARISON PREVIEW */}
            {activeTab === "comparison" && (
              <motion.div
                key="comparison"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-6"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4 flex-wrap gap-2">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#ADFF00]">
                      Visual Progress Analytics
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black text-white">
                      Side-by-Side Before & After Photo Comparison
                    </h3>
                  </div>

                  {/* Mode & Angle Controls */}
                  <div className="flex items-center gap-2">
                    <div className="bg-black/40 border border-[#1A2619] p-1 rounded-xl flex items-center gap-1">
                      <button
                        type="button"
                        onClick={() => setCompareMode("slider")}
                        className={`px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                          compareMode === "slider" ? "bg-[#ADFF00] text-black" : "text-white/60 hover:text-white"
                        }`}
                      >
                        Split Slider
                      </button>
                      <button
                        type="button"
                        onClick={() => setCompareMode("side-by-side")}
                        className={`px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                          compareMode === "side-by-side" ? "bg-[#ADFF00] text-black" : "text-white/60 hover:text-white"
                        }`}
                      >
                        Side-by-Side
                      </button>
                    </div>

                    <div className="hidden sm:flex bg-black/40 border border-[#1A2619] p-1 rounded-xl items-center gap-1">
                      {(["front", "side", "back"] as const).map((ang) => (
                        <button
                          key={ang}
                          type="button"
                          onClick={() => setCompareAngle(ang)}
                          className={`px-2.5 py-1 rounded-lg text-xs font-bold uppercase transition-all ${
                            compareAngle === ang ? "bg-white/20 text-white" : "text-white/40 hover:text-white"
                          }`}
                        >
                          {ang}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Transformation Metrics Strip */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center text-xs">
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase block">Weight Change</span>
                    <span className="text-base font-black text-emerald-400">-5.0 kg</span>
                    <span className="text-[10px] text-white/50 block">55 kg → 50 kg Target</span>
                  </div>
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase block">Body Fat</span>
                    <span className="text-base font-black text-[#ADFF00]">22.4% → 15.8%</span>
                    <span className="text-[10px] text-white/50 block">Lean Definition</span>
                  </div>
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase block">Waistline</span>
                    <span className="text-base font-black text-emerald-400">-6.0 cm</span>
                    <span className="text-[10px] text-white/50 block">99 cm → 93 cm</span>
                  </div>
                  <div className="p-3 bg-[#121E12] rounded-xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase block">Consistency</span>
                    <span className="text-base font-black text-amber-400">🔥 24 Days</span>
                    <span className="text-[10px] text-white/50 block">Active Streak</span>
                  </div>
                </div>

                {/* Visual Canvas: Split Slider or Side-by-Side */}
                {compareMode === "slider" ? (
                  <div className="space-y-3">
                    {/* Quick Preset Buttons */}
                    <div className="flex items-center justify-center gap-2">
                      <button
                        type="button"
                        onClick={() => setCompareSliderPos(90)}
                        className={`px-3 py-1 rounded-full text-xs font-bold transition-all border ${
                          compareSliderPos > 70
                            ? "bg-white/20 text-white border-white/40 shadow-sm"
                            : "bg-black/40 text-white/50 border-white/10 hover:text-white"
                        }`}
                      >
                        Show Before
                      </button>
                      <button
                        type="button"
                        onClick={() => setCompareSliderPos(50)}
                        className={`px-3 py-1 rounded-full text-xs font-bold transition-all border ${
                          compareSliderPos >= 40 && compareSliderPos <= 60
                            ? "bg-[#ADFF00] text-black border-[#ADFF00] shadow-[0_0_15px_rgba(173,255,0,0.35)]"
                            : "bg-black/40 text-white/50 border-white/10 hover:text-white"
                        }`}
                      >
                        50 / 50 Split
                      </button>
                      <button
                        type="button"
                        onClick={() => setCompareSliderPos(10)}
                        className={`px-3 py-1 rounded-full text-xs font-bold transition-all border ${
                          compareSliderPos < 30
                            ? "bg-[#ADFF00] text-black border-[#ADFF00] shadow-[0_0_15px_rgba(173,255,0,0.35)]"
                            : "bg-black/40 text-white/50 border-white/10 hover:text-white"
                        }`}
                      >
                        Show After
                      </button>
                    </div>

                    {/* Dedicated Info Row: Zero overlapping text on the photo! */}
                    <div className="flex items-center justify-between px-3.5 py-2 rounded-xl bg-[#0E170E] border border-[#1C2C1B] text-xs max-w-[340px] sm:max-w-[380px] mx-auto">
                      <div className="flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-white/40 shrink-0" />
                        <div>
                          <span className="font-bold text-white/60 block text-[10px] uppercase tracking-wider">Day 1 Baseline</span>
                          <span className="font-black text-white text-xs">55.0 kg · 22.4% BF</span>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          <span className="font-bold text-[#ADFF00] text-[10px] uppercase tracking-wider">Day 60 Goal</span>
                          <span className="w-2 h-2 rounded-full bg-[#ADFF00] shadow-[0_0_8px_#ADFF00] shrink-0" />
                        </div>
                        <span className="font-black text-[#ADFF00] text-xs">50.0 kg · 15.8% BF</span>
                      </div>
                    </div>

                    {/* Interactive Split Slider Container */}
                    <div
                      ref={sliderContainerRef}
                      onPointerDown={(e) => {
                        e.currentTarget.setPointerCapture(e.pointerId);
                        handleSliderInteraction(e.clientX);
                      }}
                      onPointerMove={(e) => {
                        if (e.buttons > 0) {
                          handleSliderInteraction(e.clientX);
                        }
                      }}
                      className="relative w-full max-w-[340px] sm:max-w-[380px] aspect-[9/14] mx-auto rounded-2xl overflow-hidden border border-[#233822] bg-[#070D07] select-none shadow-[0_16px_40px_rgba(0,0,0,0.9)] cursor-ew-resize touch-none"
                    >
                      {/* 1. Underlying Layer: AFTER Transformation */}
                      <div className="absolute inset-0">
                        <Image
                          src="/images/transformation-after.png"
                          alt="Transformed shape - Day 60"
                          fill
                          sizes="(max-width: 768px) 100vw, 380px"
                          className="object-cover object-top select-none pointer-events-none"
                          priority
                        />

                        {/* Top-Right After Mini Badge (Never overlaps) */}
                        <div className="absolute top-2.5 right-2.5 z-10 pointer-events-none">
                          <span className="px-2 py-0.5 rounded text-[10px] font-black uppercase tracking-wider bg-[#ADFF00] text-black shadow-[0_0_12px_rgba(173,255,0,0.6)] flex items-center gap-1">
                            <Trophy className="w-3 h-3" /> After
                          </span>
                        </div>
                      </div>

                      {/* 2. Foreground Layer: BEFORE Baseline (Clipped via clip-path) */}
                      <div
                        className="absolute inset-0 overflow-hidden pointer-events-none"
                        style={{ clipPath: `inset(0 ${100 - compareSliderPos}% 0 0)` }}
                      >
                        <Image
                          src="/images/transformation-before.png"
                          alt="Baseline shape - Day 1"
                          fill
                          sizes="(max-width: 768px) 100vw, 380px"
                          className="object-cover object-top select-none"
                          priority
                        />

                        {/* Top-Left Before Mini Badge (Never overlaps) */}
                        <div className="absolute top-2.5 left-2.5 z-10">
                          <span className="px-2 py-0.5 rounded text-[10px] font-black uppercase tracking-wider bg-black/75 text-white/90 border border-white/20 backdrop-blur-md flex items-center gap-1">
                            <Clock className="w-3 h-3 text-white/60" /> Before
                          </span>
                        </div>
                      </div>

                      {/* 3. Interactive Split Divider Line & Glowing Handle */}
                      <div
                        className="absolute top-0 bottom-0 w-[2px] bg-[#ADFF00] z-20 pointer-events-none shadow-[0_0_12px_rgba(173,255,0,0.9)]"
                        style={{ left: `${compareSliderPos}%` }}
                      >
                        <div className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-8 h-8 rounded-full bg-[#ADFF00] text-black flex items-center justify-center shadow-[0_0_20px_rgba(173,255,0,0.9)] font-black text-xs border-2 border-black">
                          ↔
                        </div>
                      </div>

                      {/* Hidden Accessible Range Slider */}
                      <input
                        type="range"
                        min="5"
                        max="95"
                        value={compareSliderPos}
                        onChange={(e) => setCompareSliderPos(Number(e.target.value))}
                        className="sr-only"
                        aria-label="Drag before and after split slider"
                      />
                    </div>

                    {/* Instruction Hint (Cleanly placed below the image, zero collision) */}
                    <p className="text-[11px] font-bold text-white/40 uppercase tracking-widest text-center">
                      ← Drag green slider to compare →
                    </p>
                  </div>
                ) : (
                  /* Side-by-Side Mode */
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-2xl mx-auto">
                    {/* Left Card: Before */}
                    <div className="p-4 rounded-2xl bg-[#121A12] border border-[#1E2E1D] flex flex-col justify-between">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-xs font-bold text-white/60 bg-white/5 px-2.5 py-1 rounded-full uppercase tracking-wider flex items-center gap-1.5">
                            <Clock className="w-3.5 h-3.5 text-white/40" /> Day 1 Baseline
                          </span>
                          <span className="text-xs font-bold text-white/50">55.0 kg · 22.4% BF</span>
                        </div>

                        <div className="relative aspect-[9/14] w-full rounded-xl overflow-hidden border border-white/10 my-2 bg-black/40">
                          <Image
                            src="/images/transformation-before.png"
                            alt="Baseline Check-in Photo"
                            fill
                            sizes="(max-width: 768px) 100vw, 400px"
                            className="object-cover object-top select-none pointer-events-none"
                          />
                        </div>
                      </div>

                      <div className="flex items-center justify-between text-xs text-white/50 pt-2 border-t border-white/5">
                        <span>Starting Posture & Baseline Fat</span>
                        <span className="font-bold text-white/70">Aug 9 Check-in</span>
                      </div>
                    </div>

                    {/* Right Card: After */}
                    <div className="p-4 rounded-2xl bg-[#142314] border border-[#ADFF00]/40 shadow-[0_0_30px_rgba(173,255,0,0.15)] flex flex-col justify-between">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-xs font-black text-[#ADFF00] bg-[#ADFF00]/10 px-2.5 py-1 rounded-full uppercase tracking-wider border border-[#ADFF00]/20 flex items-center gap-1.5">
                            <Trophy className="w-3.5 h-3.5 text-[#ADFF00]" /> Day 60 Transformed
                          </span>
                          <span className="text-xs font-black text-[#ADFF00]">50.0 kg · 15.8% BF</span>
                        </div>

                        <div className="relative aspect-[9/14] w-full rounded-xl overflow-hidden border border-[#ADFF00]/30 my-2 bg-black/40 shadow-[0_0_20px_rgba(173,255,0,0.1)]">
                          <Image
                            src="/images/transformation-after.png"
                            alt="Transformed Goal Photo"
                            fill
                            sizes="(max-width: 768px) 100vw, 400px"
                            className="object-cover object-top select-none pointer-events-none"
                          />
                        </div>
                      </div>

                      <div className="flex items-center justify-between text-xs text-[#ADFF00] font-bold pt-2 border-t border-[#ADFF00]/10">
                        <span>Visible 6-Pack & Muscle Tone</span>
                        <span>-5.0 kg Target Hit</span>
                      </div>
                    </div>
                  </div>
                )}

                {/* Progress CTAs */}
                <div className="p-4 rounded-xl bg-[#121F12] border border-[#213520] flex items-center justify-between text-xs text-gray-300 flex-wrap gap-2">
                  <span className="flex items-center gap-2">
                    <Camera className="w-4 h-4 text-[#ADFF00]" />
                    <span>Upload progress photos monthly to unlock visual AI comparison & measurement tracking</span>
                  </span>
                  <Link
                    href="/progress"
                    className="text-[#ADFF00] hover:underline font-bold flex items-center gap-1"
                  >
                    <span>View Progress Dashboard</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </motion.div>
            )}

            {/* 5. AI BODY VISION SCANNER PREVIEW */}
            {activeTab === "scanner" && (
              <motion.div
                key="scanner"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-6"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#ADFF00]">
                      Computer Vision Analysis
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black text-white">
                      Instant Biomechanical & Posture Scanner
                    </h3>
                  </div>
                  <div className="flex items-center gap-1.5 text-xs text-emerald-400 font-bold bg-emerald-500/10 px-3 py-1 rounded-full">
                    <ShieldCheck className="w-4 h-4" />
                    <span>Auto-Deleted After Processing</span>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
                  <div className="p-4 bg-[#121E12] rounded-2xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-1">Body Fat %</span>
                    <span className="text-2xl font-black text-[#ADFF00]">16.4%</span>
                    <span className="text-xs text-white/60 block mt-1">Lean Athletic Baseline</span>
                  </div>
                  <div className="p-4 bg-[#121E12] rounded-2xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-1">Posture Tilt</span>
                    <span className="text-2xl font-black text-emerald-400">Optimal</span>
                    <span className="text-xs text-white/60 block mt-1">Minor anterior pelvic tilt</span>
                  </div>
                  <div className="p-4 bg-[#121E12] rounded-2xl border border-[#1A2619]">
                    <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-1">Target Physique</span>
                    <span className="text-2xl font-black text-amber-400">12 Weeks</span>
                    <span className="text-xs text-white/60 block mt-1">Six-Pack Cut Roadmap</span>
                  </div>
                </div>

                <div className="p-4 rounded-2xl bg-black/40 border border-white/10 space-y-2 text-xs text-gray-300">
                  <p className="font-bold text-white flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4 text-[#ADFF00]" />
                    AI Transformation Insight:
                  </p>
                  <p className="text-gray-400 leading-relaxed">
                    "Your shoulder girdle is broad with high clavicle width. By applying a 300 kcal deficit with 150g protein and targeting upper-chest incline presses, you'll reach 11-12% body fat definition in 12 weeks."
                  </p>
                </div>
              </motion.div>
            )}

            {/* 5. 24/7 PERSONAL AI COACH PREVIEW */}
            {activeTab === "coach" && (
              <motion.div
                key="coach"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
                className="space-y-4"
              >
                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-[#ADFF00] text-black flex items-center justify-center font-black">
                      <Bot className="w-5 h-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold text-white">Luna · AI Head Coach</h3>
                      <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
                        <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                        Online 24/7 · Tailored to your active plan
                      </span>
                    </div>
                  </div>
                </div>

                {/* Simulated Conversation */}
                <div className="space-y-3 pt-2">
                  <div className="flex justify-end">
                    <div className="bg-[#1A2B1A] border border-[#2B472A] p-3.5 rounded-2xl rounded-tr-none text-xs text-white max-w-sm">
                      "I'm attending a family wedding this Saturday. What should I eat, and will it ruin my cut?"
                    </div>
                  </div>

                  <div className="flex justify-start">
                    <div className="bg-[#121E12] border border-[#1A2619] p-3.5 rounded-2xl rounded-tl-none text-xs text-gray-200 max-w-md space-y-2">
                      <p className="leading-relaxed">
                        "Not at all! Fitness is a lifestyle, not a prison. Here's your wedding game plan:"
                      </p>
                      <ul className="space-y-1 text-white/80 pl-2">
                        <li>• <strong>Target the tandoor</strong>: Eat Paneer Tikka, Chicken Tikka, or Soya Chaap first for protein.</li>
                        <li>• <strong>Choose Dal Tadka over heavy gravies</strong>: Eat with 1 roti instead of 4 naans.</li>
                        <li>• <strong>Save ~400 kcal</strong>: I've shifted 200 kcal from Thursday and Friday so your weekly deficit stays 100% on track!</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </motion.div>
            )}

          </AnimatePresence>
        </div>
      </section>

      {/* Stats Counter Bar */}
      <section className="border-y border-[#182617] bg-[#0A120A]/60 backdrop-blur-md py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          {[
            { label: "Active Athletes", value: "14,800+", icon: Users },
            { label: "AI Plans Generated", value: "45,000+", icon: Zap },
            { label: "User Satisfaction", value: "4.9 / 5.0", icon: Star },
            { label: "Indian Diet Recipes", value: "25+ Verified", icon: Utensils },
          ].map((st, i) => {
            const Icon = st.icon;
            return (
              <div key={i} className="flex flex-col items-center">
                <Icon className="w-6 h-6 text-[#ADFF00] mb-2" />
                <span className="text-3xl sm:text-4xl font-black text-white tracking-tight">
                  {st.value}
                </span>
                <span className="text-xs text-gray-400 uppercase tracking-widest font-semibold mt-1">
                  {st.label}
                </span>
              </div>
            );
          })}
        </div>
      </section>

      {/* ALL FEATURES BENTO-GRID */}
      <section id="features" className="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-4">
            <Layers className="w-4 h-4" />
            <span>Complete Architecture</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-black tracking-tight text-white">
            The Complete Fitness Operating System
          </h2>
          <p className="mt-4 text-base sm:text-lg text-gray-400">
            Engineered from the ground up for Indian athletes, students, and working professionals.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          {superpowers.map((feat, index) => {
            const Icon = feat.icon;
            return (
              <motion.div
                key={index}
                whileHover={{ y: -6 }}
                className="p-6 rounded-3xl bg-[#0D150D] border border-[#1C2C1B] hover:border-[#ADFF00]/50 transition-all shadow-[0_10px_30px_rgba(0,0,0,0.4)] flex flex-col justify-between group"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <div
                      className="w-12 h-12 rounded-2xl flex items-center justify-center border border-white/10 group-hover:scale-110 transition-transform"
                      style={{ backgroundColor: `${feat.accent}15`, color: feat.accent }}
                    >
                      <Icon className="w-6 h-6" />
                    </div>
                    <span className="text-[9px] font-extrabold uppercase tracking-wider px-2.5 py-1 rounded-full bg-black/40 text-[#ADFF00] border border-[#283D26]">
                      {feat.badge}
                    </span>
                  </div>

                  <h3 className="text-lg font-black text-white group-hover:text-[#ADFF00] transition-colors">
                    {feat.title}
                  </h3>
                  <p className="mt-2 text-xs text-gray-400 leading-relaxed font-normal">
                    {feat.desc}
                  </p>
                </div>

                <div className="mt-6 pt-3 border-t border-[#162316] flex items-center justify-between text-[11px] text-gray-500 font-bold">
                  <span>{feat.highlight}</span>
                  <CheckCircle2 className="w-4 h-4 text-[#ADFF00]" />
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* COMPARISON TABLE: Why GrindLog Beats Everything Else */}
      <section id="comparison" className="py-20 bg-[#0B120B] border-y border-[#192718]">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-4">
              <Scale className="w-4 h-4" />
              <span>Head-to-Head</span>
            </div>
            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
              Why GrindLog Beats Traditional Apps
            </h2>
            <p className="mt-4 text-gray-400 text-sm sm:text-base">
              Western apps ignore Indian diets and local budgets. Personal trainers cost ₹15,000/month. GrindLog gives you the best of both at a fraction of the price.
            </p>
          </div>

          <div className="overflow-x-auto rounded-3xl border border-[#1F301E] bg-[#0E170E] shadow-2xl">
            <table className="w-full text-left text-xs sm:text-sm">
              <thead>
                <tr className="border-b border-[#1A2619] bg-black/40">
                  <th className="p-4 sm:p-5 font-bold text-white/60 uppercase tracking-wider">Features</th>
                  <th className="p-4 sm:p-5 font-black text-[#ADFF00] uppercase tracking-wider bg-[#ADFF00]/10 border-x border-[#ADFF00]/20">
                    GRINDLOG.AI
                  </th>
                  <th className="p-4 sm:p-5 font-bold text-white/60 uppercase tracking-wider">Generic US Apps</th>
                  <th className="p-4 sm:p-5 font-bold text-white/60 uppercase tracking-wider">Personal Trainers</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#182617]">
                {comparisonItems.map((row, idx) => (
                  <tr key={idx} className="hover:bg-white/5 transition-colors">
                    <td className="p-4 sm:p-5 font-semibold text-white/90">
                      {row.feature}
                    </td>
                    <td className="p-4 sm:p-5 font-extrabold text-black bg-[#ADFF00]/15 border-x border-[#ADFF00]/20 text-center sm:text-left">
                      {row.grindlog === true ? (
                        <span className="inline-flex items-center gap-1 text-[#ADFF00] font-black">
                          <Check className="w-4 h-4 stroke-[3]" /> Yes (Built-in)
                        </span>
                      ) : (
                        <span className="text-[#ADFF00] font-black">{row.grindlog}</span>
                      )}
                    </td>
                    <td className="p-4 sm:p-5 text-gray-400">
                      {row.westernApps === false ? "❌ No" : row.westernApps}
                    </td>
                    <td className="p-4 sm:p-5 text-gray-400">
                      {row.trainer === false ? "❌ No" : row.trainer}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* REAL USER TRANSFORMATIONS */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-4">
            <Trophy className="w-4 h-4" />
            <span>Verified Results</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
            Built for Real Indian Bodies & Lifestyles
          </h2>
          <p className="mt-4 text-gray-400 text-sm sm:text-base">
            From hostel students on strict allowances to busy tech professionals, see how members transform with GrindLog.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            {
              name: "Alex R.",
              role: "College Student (Hostel Mess)",
              timeframe: "12 Weeks",
              result: "-8.5kg Fat, +4.2kg Muscle",
              quote: "The budget grocery list and PG food mode saved my life. I hit 150g protein every single day on a ₹3,000 allowance using boiled eggs, curd, and soya chunks."
            },
            {
              name: "Priya S.",
              role: "Software Engineer (WFH)",
              timeframe: "16 Weeks",
              result: "Posture Fixed & Toned Core",
              quote: "The AI Body Scanner caught my severe desk slouch on day 1. My customized 45-minute home dumbbell workouts transformed my lower back and posture."
            },
            {
              name: "Rahul M.",
              role: "Pure Vegetarian Athlete",
              timeframe: "8 Weeks",
              result: "+5.8kg Clean Mass",
              quote: "Every other app told me to eat chicken or buy 3 tubs of whey. GrindLog built delicious paneer, cheela, and dal recipes that hit my surplus effortlessly."
            }
          ].map((tf, i) => (
            <div
              key={i}
              className="p-6 rounded-3xl bg-[#101910] border border-[#1F301E] flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h4 className="font-bold text-white text-base">{tf.name}</h4>
                    <p className="text-[11px] text-white/50">{tf.role}</p>
                  </div>
                  <span className="text-xs px-2.5 py-1 rounded-full bg-[#162616] text-[#ADFF00] font-bold border border-[#254223]">
                    {tf.timeframe}
                  </span>
                </div>
                <div className="text-sm font-black text-[#ADFF00] mb-3 flex items-center gap-1.5">
                  <Flame className="w-4 h-4 text-[#ADFF00]" />
                  <span>{tf.result}</span>
                </div>
                <p className="text-xs text-gray-300 italic leading-relaxed">
                  "{tf.quote}"
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-[#182718] flex items-center justify-between text-[11px] text-gray-500 font-semibold">
                <span className="text-emerald-400">Verified Member</span>
                <span>GrindLog Pro User</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ ACCORDION SECTION */}
      <section id="faq" className="py-20 bg-[#0B120B] border-t border-[#192718]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#121E12] border border-[#273B25] text-[#ADFF00] text-xs font-bold uppercase tracking-wider mb-4">
              <MessageSquare className="w-4 h-4" />
              <span>Got Questions?</span>
            </div>
            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
              Frequently Asked Questions
            </h2>
            <p className="mt-4 text-gray-400 text-sm sm:text-base">
              Everything you need to know about GrindLog AI OS and your transformation.
            </p>
          </div>

          <div className="space-y-3">
            {faqItems.map((item, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div
                  key={idx}
                  className="rounded-2xl bg-[#0F170F] border border-[#1C2C1B] overflow-hidden transition-colors"
                >
                  <button
                    type="button"
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full p-5 text-left flex items-center justify-between gap-4 font-bold text-white text-sm sm:text-base hover:text-[#ADFF00] transition-colors"
                  >
                    <span>{item.q}</span>
                    <ChevronDown
                      className={`w-5 h-5 text-gray-400 flex-shrink-0 transition-transform duration-200 ${
                        isOpen ? "rotate-180 text-[#ADFF00]" : ""
                      }`}
                    />
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-5 text-xs sm:text-sm text-gray-300 leading-relaxed border-t border-white/5 pt-3">
                      {item.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FINAL HIGH-CONVERTING CTA SECTION */}
      <section className="py-24 relative overflow-hidden text-center">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#ADFF00]/5 to-transparent pointer-events-none" />

        <div className="max-w-4xl mx-auto px-4 relative z-10">
          <div className="w-16 h-16 rounded-3xl bg-[#121E12] border border-[#233822] text-[#ADFF00] flex items-center justify-center mx-auto mb-6 shadow-2xl">
            <Award className="w-8 h-8" />
          </div>

          <h2 className="text-4xl sm:text-6xl font-black text-white tracking-tight leading-tight">
            Your Dream Physique Isn't Luck. <br />
            <span className="text-[#ADFF00]">It's a Calculated System.</span>
          </h2>
          <p className="mt-6 text-gray-300 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
            Stop guessing your calories, wasting money on random groceries, and following generic Western workout templates. Let GrindLog build your exact plan in 2 minutes.
          </p>

          <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/auth/signup?redirect=/onboarding"
              className="w-full sm:w-auto px-10 py-5 rounded-full text-base sm:text-lg font-black uppercase tracking-wider text-black bg-[#ADFF00] hover:bg-[#c6ff47] transition-all shadow-[0_0_40px_rgba(173,255,0,0.5)] hover:scale-105 active:scale-95 flex items-center justify-center gap-3 group"
            >
              <span>Start My Free Transformation Now</span>
              <ArrowRight className="w-6 h-6 group-hover:translate-x-1.5 transition-transform" />
            </Link>
          </div>

          <p className="mt-4 text-xs text-gray-500 font-semibold">
            No credit card required · Free preview plan generated instantly
          </p>
        </div>
      </section>

      {/* Polished Footer */}
      <footer className="border-t border-[#182617] py-10 bg-[#070C07] text-xs text-gray-500">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-[#ADFF00] text-black flex items-center justify-center font-black text-sm">
              G
            </div>
            <span>© 2026 GrindLog AI OS. Engineered for Indian Fitness.</span>
          </div>

          <div className="flex flex-wrap items-center gap-6">
            <a href="#showcase" className="hover:text-white transition-colors">Live App</a>
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#comparison" className="hover:text-white transition-colors">Comparison</a>
            <a href="#faq" className="hover:text-white transition-colors">FAQ</a>
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link href="/auth/signup?redirect=/onboarding" className="text-[#ADFF00] font-bold hover:underline">
              Start Free →
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
