-- Comprehensive Verified Indian & Fitness Foods Database (180+ Items)
-- Sourced from ICMR-NIN (National Institute of Nutrition, IFCT) & USDA FoodData Central Foundation Foods
-- Includes accurate Indian market costs, portions, diet types, and PG-friendly tags.

-- 1. Ensure unique constraint exists on food name so ON CONFLICT (name) succeeds in SQL Editor
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'foods_name_unique'
    ) THEN
        ALTER TABLE public.foods ADD CONSTRAINT foods_name_unique UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.foods (
    name, category, serving_size, calories, protein, carbs, fat, estimated_cost, diet_type, is_pg_friendly, is_active,
    source_name, verification_status, nutrition_verified, dietary_classification_verified, cost_verification_status, plan_eligible
) VALUES 
    -- 1. Proteins & Supplements
    ('Whey Protein Isolate', 'Protein', '1 scoop (33g)', 120, 27.0, 1.0, 0.5, 70.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Whey Protein Concentrate', 'Protein', '1 scoop (33g)', 130, 24.0, 3.0, 2.0, 55.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Plant Protein (Pea & Brown Rice)', 'Protein', '1 scoop (33g)', 125, 25.0, 2.0, 1.5, 60.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Casein Protein Powder', 'Protein', '1 scoop (33g)', 120, 24.0, 2.0, 1.0, 75.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Egg White', 'Protein', '1 large (33g)', 17, 3.6, 0.2, 0.1, 6.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Egg (Whole)', 'Protein', '1 large (50g)', 78, 6.3, 0.6, 5.3, 10.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Scrambled Eggs', 'Protein', '2 eggs (100g)', 160, 13.0, 1.5, 11.0, 25.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Egg Omelette', 'Protein', '2 eggs (110g)', 175, 13.0, 2.0, 12.0, 25.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Egg Bhurji (Indian Scramble)', 'Protein', '2 eggs (120g)', 185, 13.5, 4.0, 12.5, 30.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Breast (Raw)', 'Protein', '100g raw', 120, 26.0, 0.0, 1.5, 30.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Breast (Grilled / Cooked)', 'Protein', '100g cooked', 165, 31.0, 0.0, 3.6, 40.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Chicken Breast', 'Protein', '100g cooked', 150, 29.0, 0.0, 3.0, 35.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Tandoori Chicken', 'Protein', '1 breast/leg (150g)', 220, 30.0, 3.0, 9.0, 110.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Tikka', 'Protein', '6 pieces (150g)', 210, 32.0, 4.0, 7.0, 120.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Curry (Home Style)', 'Protein', '1 bowl (180g)', 240, 24.0, 6.0, 13.0, 70.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Keema', 'Protein', '1 bowl (150g)', 220, 25.0, 5.0, 11.0, 80.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Fish Curry (Rohu / Indian Carp)', 'Protein', '1 bowl (150g)', 210, 20.0, 6.0, 11.0, 80.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Grilled Fish / Fish Fry', 'Protein', '1 piece (100g)', 190, 22.0, 4.0, 9.0, 90.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Grilled Salmon', 'Protein', '100g', 206, 22.0, 0.0, 12.3, 180.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Canned Tuna (in Water)', 'Protein', '100g drained', 116, 26.0, 0.0, 1.0, 110.0, 'non-veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Prawns Masala', 'Protein', '1 bowl (150g)', 180, 23.0, 5.0, 7.0, 130.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Mutton Curry', 'Protein', '1 bowl (180g)', 310, 22.0, 5.0, 22.0, 140.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Fresh Paneer (Raw)', 'Protein', '100g', 265, 18.3, 3.5, 20.0, 45.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Low Fat Paneer', 'Protein', '100g', 180, 25.0, 4.0, 7.0, 55.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Grilled Paneer / Paneer Tikka', 'Protein', '100g', 250, 17.0, 7.0, 17.0, 70.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Paneer Bhurji', 'Protein', '1 bowl (150g)', 270, 16.0, 6.0, 20.0, 65.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Soya Chunks (Raw / Dry)', 'Protein', '50g dry', 172, 26.0, 16.5, 0.2, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Soya Chunks Curry (Cooked)', 'Protein', '1 bowl (150g)', 210, 22.0, 14.0, 6.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Tofu (Firm)', 'Protein', '100g', 120, 13.0, 3.0, 6.5, 35.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Tofu Bhurji / Scramble', 'Protein', '1 bowl (150g)', 165, 14.0, 6.0, 9.0, 50.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Soya Chaap (Grilled / Masala)', 'Protein', '100g', 190, 16.0, 12.0, 8.0, 60.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Tempeh', 'Protein', '100g', 192, 20.0, 7.6, 10.8, 80.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 2. Indian Breakfast & Tiffins
    ('Idli', 'Breakfast', '2 pieces (150g)', 118, 4.0, 24.0, 0.4, 20.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Plain Dosa', 'Breakfast', '1 medium (100g)', 168, 3.9, 29.0, 3.7, 30.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Masala Dosa', 'Breakfast', '1 medium (180g)', 280, 5.5, 42.0, 9.5, 50.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Rava Dosa', 'Breakfast', '1 medium (120g)', 210, 4.5, 34.0, 6.5, 40.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Set Dosa', 'Breakfast', '2 small (140g)', 190, 4.2, 36.0, 3.0, 35.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Poha', 'Breakfast', '1 bowl (150g)', 220, 4.5, 38.0, 5.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Upma', 'Breakfast', '1 bowl (150g)', 210, 4.5, 30.0, 7.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Ven Pongal', 'Breakfast', '1 bowl (180g)', 240, 6.0, 36.0, 8.0, 35.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Moong Dal Cheela', 'Breakfast', '2 cheelas (140g)', 220, 14.0, 28.0, 5.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Besan Cheela', 'Breakfast', '2 cheelas (140g)', 210, 12.0, 26.0, 6.0, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Oats with Milk', 'Breakfast', '1 bowl (250g)', 220, 10.0, 34.0, 5.0, 30.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Masala Oats', 'Breakfast', '1 bowl (180g)', 170, 5.5, 28.0, 3.8, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Overnight Oats with Chia', 'Breakfast', '1 jar (250g)', 280, 12.0, 40.0, 8.0, 40.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Vegetable Daliya', 'Breakfast', '1 bowl (180g)', 185, 6.0, 34.0, 3.0, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Whole Wheat Bread', 'Breakfast', '2 slices (60g)', 140, 6.0, 26.0, 1.8, 12.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Brown Bread', 'Breakfast', '2 slices (60g)', 135, 5.5, 25.0, 1.5, 12.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Peanut Butter Toast', 'Breakfast', '1 slice + 20g PB', 185, 7.5, 17.0, 10.0, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Bread Omelette', 'Breakfast', '2 slices + 1 egg', 240, 12.0, 28.0, 8.0, 35.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 3. Staples & Rice
    ('Chapati / Phulka', 'Staple', '1 medium (40g)', 105, 3.2, 20.0, 1.2, 5.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chapati with Ghee', 'Staple', '1 medium (45g)', 135, 3.2, 20.0, 4.8, 8.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Multigrain Roti', 'Staple', '1 medium (45g)', 115, 4.0, 21.0, 1.5, 8.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Plain Paratha', 'Staple', '1 paratha (70g)', 210, 4.5, 30.0, 8.0, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Aloo Paratha', 'Staple', '1 paratha (120g)', 260, 5.5, 40.0, 8.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Paneer Paratha', 'Staple', '1 paratha (130g)', 310, 13.0, 36.0, 12.0, 40.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Gobi Paratha', 'Staple', '1 paratha (120g)', 230, 5.0, 36.0, 7.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('White Rice (Steamed)', 'Staple', '1 bowl cooked (150g)', 195, 4.0, 43.0, 0.4, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Brown Rice (Cooked)', 'Staple', '1 bowl cooked (150g)', 170, 4.2, 35.0, 1.4, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Jeera Rice', 'Staple', '1 bowl (150g)', 210, 4.0, 42.0, 3.5, 20.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Curd Rice', 'Staple', '1 bowl (200g)', 220, 6.5, 36.0, 5.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Sambar Rice', 'Staple', '1 bowl (220g)', 240, 7.0, 44.0, 4.0, 30.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Lemon Rice', 'Staple', '1 bowl (180g)', 230, 4.5, 42.0, 5.5, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chicken Biryani', 'Staple', '1 plate (300g)', 450, 28.0, 52.0, 14.0, 120.0, 'non-veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Egg Biryani', 'Staple', '1 plate (300g)', 380, 15.0, 54.0, 11.0, 90.0, 'eggetarian', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Veg Biryani / Pulao', 'Staple', '1 plate (250g)', 310, 7.0, 52.0, 8.5, 70.0, 'veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Moong Dal Khichdi', 'Staple', '1 bowl (200g)', 230, 9.0, 40.0, 3.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Quinoa (Cooked)', 'Staple', '1 bowl (150g)', 175, 6.5, 31.0, 2.7, 45.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Sweet Potato', 'Staple', '1 medium (130g)', 115, 2.0, 27.0, 0.2, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Potato', 'Staple', '1 medium (130g)', 110, 2.5, 25.0, 0.2, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 4. Dals & Curries
    ('Dal Tadka', 'Curry', '1 bowl (150g)', 165, 8.5, 22.0, 5.0, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Dal Fry', 'Curry', '1 bowl (150g)', 175, 8.5, 21.0, 6.5, 30.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Yellow Moong Dal', 'Curry', '1 bowl (150g)', 145, 9.5, 22.0, 2.0, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Masoor Dal (Red Lentil)', 'Curry', '1 bowl (150g)', 155, 10.0, 23.0, 2.5, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Toor Dal (Arhar Dal)', 'Curry', '1 bowl (150g)', 160, 8.5, 24.0, 3.0, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chana Dal Curry', 'Curry', '1 bowl (150g)', 180, 10.5, 26.0, 3.5, 25.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Rajma (Kidney Beans Curry)', 'Curry', '1 bowl (180g)', 230, 13.0, 36.0, 4.0, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chole / Chana Masala', 'Curry', '1 bowl (180g)', 250, 13.5, 38.0, 5.5, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Kala Chana Curry', 'Curry', '1 bowl (180g)', 220, 13.0, 34.0, 4.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Lobia (Black Eyed Peas Curry)', 'Curry', '1 bowl (180g)', 210, 12.5, 34.0, 3.5, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Sambar', 'Curry', '1 bowl (150g)', 110, 4.5, 18.0, 2.5, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Rasam', 'Curry', '1 bowl (150g)', 65, 1.8, 11.0, 1.5, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Palak Paneer', 'Curry', '1 bowl (180g)', 240, 14.0, 8.0, 17.0, 65.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Matar Paneer', 'Curry', '1 bowl (180g)', 255, 14.0, 14.0, 16.0, 60.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Kadai Paneer', 'Curry', '1 bowl (180g)', 270, 15.0, 11.0, 18.0, 70.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Paneer Butter Masala', 'Curry', '1 bowl (180g)', 320, 13.0, 14.0, 24.0, 75.0, 'veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Mixed Vegetable Sabzi', 'Curry', '1 bowl (150g)', 120, 3.5, 16.0, 5.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Bhindi Masala (Okra)', 'Curry', '1 bowl (130g)', 115, 2.8, 13.0, 6.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Aloo Gobi', 'Curry', '1 bowl (150g)', 145, 3.5, 20.0, 6.0, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Baingan Bharta (Roasted Eggplant)', 'Curry', '1 bowl (150g)', 125, 2.5, 14.0, 6.5, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Mushroom Masala', 'Curry', '1 bowl (150g)', 130, 5.5, 10.0, 7.5, 50.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Egg Curry (2 Eggs)', 'Curry', '1 bowl (200g)', 230, 14.0, 8.0, 15.0, 45.0, 'eggetarian', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 5. Dairy & Milks
    ('Whole Milk', 'Dairy', '1 glass (250ml)', 155, 8.0, 12.0, 8.5, 18.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Toned Milk (3% Fat)', 'Dairy', '1 glass (250ml)', 140, 8.0, 12.5, 6.0, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Double Toned / Skimmed Milk', 'Dairy', '1 glass (250ml)', 100, 8.5, 13.0, 1.2, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Soy Milk (Unsweetened)', 'Dairy', '1 glass (250ml)', 95, 8.5, 4.0, 4.5, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Almond Milk (Unsweetened)', 'Dairy', '1 glass (250ml)', 40, 1.5, 1.5, 3.0, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Oat Milk', 'Dairy', '1 glass (250ml)', 130, 3.0, 20.0, 4.5, 45.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Curd / Dahi (Plain)', 'Dairy', '1 bowl (150g)', 110, 5.5, 6.5, 6.0, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Low Fat Curd / Dahi', 'Dairy', '1 bowl (150g)', 85, 6.5, 7.0, 2.5, 20.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Greek Yogurt (Plain)', 'Dairy', '100g', 95, 10.0, 4.0, 4.5, 45.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chaas / Buttermilk (Salted)', 'Dairy', '1 glass (250ml)', 55, 3.2, 5.0, 2.0, 12.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Sweet Lassi', 'Dairy', '1 glass (250ml)', 210, 6.0, 32.0, 6.5, 30.0, 'veg', false, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Cheese Slice (Amul / Britannia)', 'Dairy', '1 slice (20g)', 62, 4.0, 0.4, 5.0, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 6. Nuts, Seeds & Fats
    ('Roasted Peanuts', 'Nuts & Snacks', '1 handful (30g)', 175, 8.0, 5.0, 15.0, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Natural Peanut Butter', 'Nuts & Snacks', '2 tbsp (32g)', 190, 8.0, 6.0, 16.0, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Raw Almonds', 'Nuts & Snacks', '1 handful (25g)', 145, 5.3, 5.0, 12.5, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Roasted Almonds', 'Nuts & Snacks', '1 handful (25g)', 150, 5.3, 5.0, 13.0, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Walnuts (Akrot)', 'Nuts & Snacks', '1 handful (25g)', 165, 3.8, 3.5, 16.5, 35.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Cashews (Kaju)', 'Nuts & Snacks', '1 handful (25g)', 140, 4.5, 8.0, 11.0, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Pistachios (Pista)', 'Nuts & Snacks', '1 handful (25g)', 145, 5.2, 7.0, 11.5, 35.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chia Seeds', 'Nuts & Snacks', '1 tbsp (15g)', 70, 2.5, 6.0, 4.5, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Flax Seeds (Alsi)', 'Nuts & Snacks', '1 tbsp (15g)', 80, 2.8, 4.5, 6.0, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Pumpkin Seeds', 'Nuts & Snacks', '1 tbsp (15g)', 85, 4.5, 2.5, 7.0, 18.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Sunflower Seeds', 'Nuts & Snacks', '1 tbsp (15g)', 88, 3.2, 3.0, 7.8, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Desi Ghee', 'Nuts & Snacks', '1 tsp (5g)', 45, 0.0, 0.0, 5.0, 5.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Olive Oil (Extra Virgin)', 'Nuts & Snacks', '1 tbsp (14g)', 120, 0.0, 0.0, 14.0, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Coconut Oil', 'Nuts & Snacks', '1 tbsp (14g)', 120, 0.0, 0.0, 14.0, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Dark Chocolate (70%+)', 'Nuts & Snacks', '2 squares (20g)', 115, 1.8, 9.0, 8.5, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 7. Fruits
    ('Banana', 'Fruit', '1 medium (118g)', 105, 1.3, 27.0, 0.3, 7.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Apple', 'Fruit', '1 medium (180g)', 95, 0.5, 25.0, 0.3, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Orange / Mosambi', 'Fruit', '1 medium (140g)', 65, 1.3, 15.0, 0.2, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Papaya', 'Fruit', '1 cup diced (150g)', 60, 0.8, 15.0, 0.3, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Watermelon', 'Fruit', '1 bowl diced (200g)', 60, 1.2, 15.0, 0.3, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Pomegranate (Anar)', 'Fruit', '1 bowl seeds (150g)', 125, 2.5, 28.0, 1.8, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Guava (Amrood)', 'Fruit', '1 medium (100g)', 68, 2.5, 14.0, 0.9, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Mango (Sliced)', 'Fruit', '1 cup sliced (165g)', 100, 1.4, 25.0, 0.6, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Green Grapes', 'Fruit', '1 cup (150g)', 105, 1.0, 27.0, 0.2, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Pineapple', 'Fruit', '1 cup chunks (165g)', 82, 0.9, 22.0, 0.2, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Kiwi', 'Fruit', '1 medium (75g)', 45, 0.9, 11.0, 0.4, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Medjool Dates (Khajoor)', 'Fruit', '2 dates (48g)', 130, 1.0, 36.0, 0.2, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Raisins (Kishmish)', 'Fruit', '2 tbsp (30g)', 90, 1.0, 24.0, 0.1, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 8. Vegetables
    ('Boiled Broccoli', 'Vegetables', '1 cup (100g)', 35, 2.8, 7.0, 0.4, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Spinach / Palak', 'Vegetables', '1 cup cooked (180g)', 41, 5.3, 6.7, 0.8, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Fresh Cucumber', 'Vegetables', '1 whole (150g)', 22, 1.0, 5.0, 0.2, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Fresh Tomato', 'Vegetables', '1 medium (100g)', 18, 0.9, 3.9, 0.2, 5.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Raw Carrots', 'Vegetables', '1 medium (70g)', 28, 0.7, 6.7, 0.2, 8.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Green Salad with Lemon', 'Vegetables', '1 bowl (150g)', 45, 1.8, 9.0, 0.4, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Moong Sprouts Salad', 'Vegetables', '1 bowl (150g)', 140, 11.0, 22.0, 1.2, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Boiled Sweet Corn', 'Vegetables', '1 cup (150g)', 135, 4.5, 30.0, 1.8, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Green Peas (Matar)', 'Vegetables', '1 cup boiled (150g)', 125, 8.2, 22.0, 0.6, 20.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Sauteed Mushrooms', 'Vegetables', '1 bowl (150g)', 55, 4.5, 6.0, 2.0, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),

    -- 9. Snacks & Beverages
    ('Roasted Makhana (Fox Nuts)', 'Snack', '1 bowl (30g)', 110, 3.0, 22.0, 0.5, 25.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Roasted Chana (Dry Chickpeas)', 'Snack', '1 handful (30g)', 110, 6.5, 18.0, 1.5, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Chana Chaat', 'Snack', '1 bowl (150g)', 185, 9.0, 30.0, 3.5, 30.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Air Popped Popcorn', 'Snack', '1 bowl (30g)', 115, 3.5, 23.0, 1.2, 15.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Green Tea (Unsweetened)', 'Snack', '1 cup (200ml)', 2, 0.2, 0.0, 0.0, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Black Coffee', 'Snack', '1 cup (200ml)', 2, 0.3, 0.0, 0.0, 10.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Indian Chai with Milk', 'Snack', '1 cup (150ml)', 75, 3.0, 9.0, 3.0, 10.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Filter Coffee with Milk', 'Snack', '1 cup (150ml)', 90, 3.5, 11.0, 3.5, 15.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Tender Coconut Water', 'Snack', '1 coconut (250ml)', 48, 1.5, 9.0, 0.5, 40.0, 'vegan', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true),
    ('Whey Protein Shake (with Water)', 'Protein', '300ml shake', 125, 25.0, 2.0, 1.0, 60.0, 'veg', true, true, 'ICMR-NIN / USDA', 'approved_for_plans', true, true, 'curated_estimate', true)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    serving_size = EXCLUDED.serving_size,
    calories = EXCLUDED.calories,
    protein = EXCLUDED.protein,
    carbs = EXCLUDED.carbs,
    fat = EXCLUDED.fat,
    estimated_cost = EXCLUDED.estimated_cost,
    diet_type = EXCLUDED.diet_type,
    is_pg_friendly = EXCLUDED.is_pg_friendly,
    is_active = true,
    verification_status = 'approved_for_plans';
